QAT:
    fully_quantized: False
    device: 'cuda'
    data_quantization:
      status: On
      bits: 6
      custom_bits: { }
      symmetric: False
      quantization_mode: dynamic
      observer: 'MinMax'
      per_channel: True

    weights_quantization:
      status: On
      bits: 6
      symmetric: False
      custom_bits:  {}
      per_channel: True
